#------------------------------------------------------------------------------
# usage: configure tutor MySQL email service
#------------------------------------------------------------------------------
name: Open edX Tutor k8s configure MySQL service
description: Github Action to use Tutor to configure a remote MySQL service for use with Open edX running on AWS EKS Kubernetes
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namespace to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    # retrieve the MySQL connection parameters that we created in Terraform
    # and then stored in Kubernetes secrets. These include:
    #   MYSQL_HOST: mysql.app.yourschool.edu
    #   MYSQL_PORT: "3306"
    #   OPENEDX_MYSQL_USERNAME: openedx
    #   OPENEDX_MYSQL_PASSWORD: **************
    #   MYSQL_ROOT_USERNAME: root
    #   MYSQL_ROOT_PASSWORD: *************
    - name: fetch MySQL root configuration from Kubernetes secrets
      id: get-root-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-root

    - name: fetch MySQL openedx configuration from Kubernetes secrets
      id: get-openedx-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-openedx

    - name: set environment variables
      id: set-environment-variables
      shell: bash
      run: echo "TUTOR_RUN_MYSQL=false" >> $GITHUB_ENV

    - name: configure tutor
      id: save-config
      shell: bash
      run: tutor config save
